/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FormField {
        "error": string;
        "label"?: string;
        "maxlength"?: number;
        "minlength"?: number;
        "name": string;
        "options"?: { value: string; label: string }[];
        "pattern"?: string;
        "placeholder"?: string;
        "required"?: boolean;
        "type": string;
        "value"?: string;
    }
    interface FormNavigation {
        "currentStep": number;
        "disableNext": boolean;
        "maxStep": number;
        "navigateStep": (step: number) => void;
    }
    interface FormStep {
        "step": number;
    }
    interface FormStepper {
    }
    interface StepperStatus {
    }
}
export interface FormFieldCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFormFieldElement;
}
declare global {
    interface HTMLFormFieldElementEventMap {
        "valueChanged": { name: string; value: string; valid: boolean };
    }
    interface HTMLFormFieldElement extends Components.FormField, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFormFieldElementEventMap>(type: K, listener: (this: HTMLFormFieldElement, ev: FormFieldCustomEvent<HTMLFormFieldElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFormFieldElementEventMap>(type: K, listener: (this: HTMLFormFieldElement, ev: FormFieldCustomEvent<HTMLFormFieldElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFormFieldElement: {
        prototype: HTMLFormFieldElement;
        new (): HTMLFormFieldElement;
    };
    interface HTMLFormNavigationElement extends Components.FormNavigation, HTMLStencilElement {
    }
    var HTMLFormNavigationElement: {
        prototype: HTMLFormNavigationElement;
        new (): HTMLFormNavigationElement;
    };
    interface HTMLFormStepElement extends Components.FormStep, HTMLStencilElement {
    }
    var HTMLFormStepElement: {
        prototype: HTMLFormStepElement;
        new (): HTMLFormStepElement;
    };
    interface HTMLFormStepperElement extends Components.FormStepper, HTMLStencilElement {
    }
    var HTMLFormStepperElement: {
        prototype: HTMLFormStepperElement;
        new (): HTMLFormStepperElement;
    };
    interface HTMLStepperStatusElement extends Components.StepperStatus, HTMLStencilElement {
    }
    var HTMLStepperStatusElement: {
        prototype: HTMLStepperStatusElement;
        new (): HTMLStepperStatusElement;
    };
    interface HTMLElementTagNameMap {
        "form-field": HTMLFormFieldElement;
        "form-navigation": HTMLFormNavigationElement;
        "form-step": HTMLFormStepElement;
        "form-stepper": HTMLFormStepperElement;
        "stepper-status": HTMLStepperStatusElement;
    }
}
declare namespace LocalJSX {
    interface FormField {
        "error"?: string;
        "label"?: string;
        "maxlength"?: number;
        "minlength"?: number;
        "name": string;
        "onValueChanged"?: (event: FormFieldCustomEvent<{ name: string; value: string; valid: boolean }>) => void;
        "options"?: { value: string; label: string }[];
        "pattern"?: string;
        "placeholder"?: string;
        "required"?: boolean;
        "type"?: string;
        "value"?: string;
    }
    interface FormNavigation {
        "currentStep"?: number;
        "disableNext"?: boolean;
        "maxStep"?: number;
        "navigateStep"?: (step: number) => void;
    }
    interface FormStep {
        "step"?: number;
    }
    interface FormStepper {
    }
    interface StepperStatus {
    }
    interface IntrinsicElements {
        "form-field": FormField;
        "form-navigation": FormNavigation;
        "form-step": FormStep;
        "form-stepper": FormStepper;
        "stepper-status": StepperStatus;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "form-field": LocalJSX.FormField & JSXBase.HTMLAttributes<HTMLFormFieldElement>;
            "form-navigation": LocalJSX.FormNavigation & JSXBase.HTMLAttributes<HTMLFormNavigationElement>;
            "form-step": LocalJSX.FormStep & JSXBase.HTMLAttributes<HTMLFormStepElement>;
            "form-stepper": LocalJSX.FormStepper & JSXBase.HTMLAttributes<HTMLFormStepperElement>;
            "stepper-status": LocalJSX.StepperStatus & JSXBase.HTMLAttributes<HTMLStepperStatusElement>;
        }
    }
}
